### ISSUE TITLE
Front-end, Scene tile, featured image not showing correcting for 256 px image

### ISSUE THREAD

**Issue by jimver04** [DigiArt-project/WordpressUnity3DEditor#100]
Try to set a 256x256 jpg as featured image for a scene. It is not viewed correctly in the tile. Should we give specifications for the size?

**Comment by tpapaz** [comment]
Fixed it with some additional css rules. 
Now it will work for any image size

In e3dbda29a797b53a72aedeb3c8b8a090154b9f8f
