### ISSUE TITLE
Producer Power Production Values save as Array not String

### ISSUE THREAD

**Issue by stathisnikolaidis** [DigiArt-project/WordpressUnity3DEditor#103]

**Comment by jimver04** [comment]
I have made a fiddle

https://jsfiddle.net/9g7c2y38/18/

it is in js so open the console to see the result. I guess it is the same in php.

**Comment by jimver04** [comment]
![image](https://user-images.githubusercontent.com/1898502/29869029-e37ad986-8d89-11e7-92e1-9829783c3a6a.png)


Stathi you use both values of the [x,y]
json: [[0,0],[0,1],[0,2] .., [x,y], ...   [27,5]]

only y should be inserted as value to array not both
