### ISSUE TITLE
No colour on the textured 3D assets

### ISSUE THREAD

**Issue by aauEnvisage** [DigiArt-project/WordpressUnity3DEditor#109]
Created 3D assets with accompanying colourful textures. But in the scene they just appear as white object. 
Worked in Chrome on a PC.

**Comment by jimver04** [comment]
Hi can you sent the 3D assets to me at:         jimver04 at gmail.com    ?

**Comment by aauEnvisage** [comment]
We have downloaded the 3D assets the authoring tool proposes 
Help: Packet of 3D models for game type: Energy, which leads to the following drop box link: https://www.dropbox.com/s/0ed7f9c6v4qnsnl/paketo_3d_v3.zip?dl=0
