### ISSUE TITLE
Missing texture on toggle box

### ISSUE THREAD

**Issue by aauEnvisage** [DigiArt-project/WordpressUnity3DEditor#110]
Each object selected in the 3D scene has a pink box that when clicked toggles between move, rotate and scale mode.
- the pink indicates that is missing some texture

Again as seen in chrome on a pc.

![cat_pink unity jpg](https://user-images.githubusercontent.com/31509073/29922672-defa73ee-8e56-11e7-92a8-130916746819.jpg)

**Comment by jimver04** [comment]
Which color do you prefer ?

**Comment by jimver04** [comment]
I have put orange
