### ISSUE TITLE
Deleting and renaming predefined scenes not possible

### ISSUE THREAD

**Issue by aauEnvisage** [DigiArt-project/WordpressUnity3DEditor#111]
Is this a feature or a bug?

**Comment by jimver04** [comment]
Deleting will be ready today.
Editing is not completed yet

**Comment by tpapaz** [comment]
@jimver04 -> Correction: Edit is working. (the title has been updated)

**Comment by tpapaz** [comment]
Hello @aauEnvisage, it is crucial for the platform that the predefined scenes cannot be deleted. It's a feature :)

We haven't decided yet on the rename functionality, standby.

**Comment by aauEnvisage** [comment]
Okay, it's a feature then :)

**Comment by tpapaz** [comment]
Possible duplicate of #112

**Comment by tpapaz** [comment]
@aauEnvisage We are implementing title & description renaming. Delete action is solidified as a no-no. :)
Closing the issue, we can keep track of it in #112.
