### ISSUE TITLE
Can't rename scenes after creating them

### ISSUE THREAD

**Issue by aauEnvisage** [DigiArt-project/WordpressUnity3DEditor#112]

**Comment by jimver04** [comment]
It is part of the editing procedure that we are implementing now

**Comment by jimver04** [comment]
Put it in blue ribbon of 3d editor

**Comment by tpapaz** [comment]
> **Also adding a description edit feature**

**Comment by tpapaz** [comment]
The front end is ready. We must now connect this with the saving functionality. (Loading pre-existing data works)
