### ISSUE TITLE
No link to authoring tool when user is already logged in

### ISSUE THREAD

**Issue by aauEnvisage** [DigiArt-project/WordpressUnity3DEditor#113]
If a user has already logged in via the login field on the frontpage but then navigates away from the site. And later then opens the frontpage of the authoring tool then there is no easy way to access the authoring tool. The login field is gone (since the user is logged) but has not replaced with a link to the authoring tool. The user has to log out and the login again. 
This is extremely confusing, especially you find your way to the wordpress backend.

**Comment by jimver04** [comment]
It is going to be fixed

**Comment by jimver04** [comment]
Fixed
