### ISSUE TITLE
Can not edit a "Producer"

### ISSUE THREAD

**Issue by jimver04** [DigiArt-project/WordpressUnity3DEditor#133]
It does not display the field of producer. The other categories are ok.

It says game = 0

http://127.0.0.1:8080/digiart-project_Jan17/wpunity-3d-asset-creator/?wpunity_game=0&wpunity_scene=1282&wpunity_asset=1385

This breaks the breadcrump also

![image](https://user-images.githubusercontent.com/1898502/30266194-4e67a6fa-96e7-11e7-863b-5912079b10b4.png)

**Comment by tpapaz** [comment]
The url you provided is local: 127.0.0.1. I can't test this.
