### ISSUE TITLE
Turbine flot plot in graph values do not show well on zoom in-out

### ISSUE THREAD

**Issue by jimver04** [DigiArt-project/wordpressunity3deditor#136]
I think it is better to remove them completely and put them above sliders

![image](https://user-images.githubusercontent.com/1898502/30313276-6d9d24b4-97a5-11e7-9165-148f35f34fa2.png)

**Comment by tpapaz** [comment]
Did we deleted the graph from the plugin? If so we must close this (and delete a library I was loading to create this)

**Comment by jimver04** [comment]
Yes it is deleted. Apart from the library remove also some configuration options. I did not try to remove them since they are in many places.
Thanks,
D.
