### ISSUE TITLE
Create Asset with multiple 3d files selection

### ISSUE THREAD

**Issue by jimver04** [DigiArt-project/WordpressUnity3DEditor#144]
Taso,

1. Test that my unit test is working properly:
            wp-content/plugins/wordpressunity3deditor/js_libs/test_ww_objloader.html

2. Try to pass the code from

        test_ww_objloader.html

inside 

the    
js_libs\wpunity_asset_editor_scripts.js       and
templates\edit-wpunity_asset3D.php

files

HINTs:
You must register also the  following js

```
<!-- The new 87 three js functions -->
<script src="threejs87/three.js"></script>
<script src="threejs87/TrackballControls.js"></script>
<script src="threejs87/MTLLoader.js"></script>
<script src="threejs87/OBJLoader2.js"></script>
<script src="threejs87/WWOBJLoader2.js"></script>
<script src="wu_webw_3d_view.js"></script>
```

**Comment by tpapaz** [comment]
It works, with a progress bar too. check db8f97b7728343d4d256343d738271665aa2f451
