### ISSUE TITLE
jquery ui js and css

### ISSUE THREAD

**Issue by jimver04** [DigiArt-project/WordpressUnity3DEditor#148]
Taso,

1.11.4 of  wp-includes/js/jquery/ui/widget.min.css is not forward compatible with jquery 1.12 in js_libs/jquery

action: plz change  jquery ui js and css libraries to version 1.11.4 in js_libs/jquery/

**Comment by tpapaz** [comment]
Implemented loading of WordPress's integrated jQuery UI library to avoid future conflicts
