### ISSUE TITLE
How to add a 3rd template

### ISSUE THREAD

**Issue by jimver04** [DigiArt-project/WordpressUnity3DEditor#150]
Stathi in the master branch we need one more game type, namely Chemistry. It is important for me to know the procedure.
1) Can you describe how to add a new game type? Which files need modifications?
    - Scenes should be the same with Energy type of games
    - No asset types for the time being

**Comment by stathisnikolaidis** [comment]
Step 1
- Create wpunity-default-chemistry-project-settings.php file at includes/default_game_project_settings/
- Copy/Paste data from another template file
- Change main function name (wpunity_games_taxtype_fill_chemistry) and add_action at the end of the file
- Change "wp_insert_term" arguments (line 1488 -> term, descriptin,slug) & $inserted_term (get_term_by arguments same as newly inserted slug)
- Include php file at main plugin file "WordpressUnity3DEditor-functions.php":
include_once( plugin_dir_path( __FILE__ ) . 'includes/default_game_project_settings/wpunity-default-chemistry-project-settings.php' );

**Comment by stathisnikolaidis** [comment]
Step 2
- Create YAMLs for each different Scene

**Comment by stathisnikolaidis** [comment]
Step 3
- Create Auto-Generated Scenes on Game Creation (@ frontend)
- Set default template for user's scenes

**Comment by stathisnikolaidis** [comment]
Step 3
- Create Asset Types
