### ISSUE TITLE
Yaml for POI video does not include the video attachment

### ISSUE THREAD

**Issue by stathisnikolaidis** [DigiArt-project/WordpressUnity3DEditor#161]

**Comment by jimver04** [comment]
Sorry I forgot it. Now it is added in #155 POI Video.  You do not have to replace everything

add this 

    - target: {fileID: 114895655547013306, guid: 007c17ee709168148aa4aa7afd9e1076,
        type: 2}
      propertyPath: videoToShow
      value: bunny_video
      objectReference: {fileID: 0}


and replace bunny_video with `___[poi_v_v_name]___`    where the latter is the name of the video file. :)
