### ISSUE TITLE
Game version number input

### ISSUE THREAD

**Issue by jimver04** [DigiArt-project/WordpressUnity3DEditor#163]
Keep a record of versions

Add a new table in database

```
Columns    
  id      game_project_id           version_number            date_generated
( INT )        ( INT )                   ( INT <= 9999 )            (     DATE   )               
   1              520                         1                        2017-10-18 5:00:35
   2              499                         1                        2017-10-18 6:00:35
   3              520                         2                        2017-10-19 6:00:35
   4              520                         3                        2017-10-19 7:00:35
   5              499                         2                        2017-10-19 8:00:35
```
Each row is generated when the "PROCEED" button of  compile window is pressed.

@stathisnikolaidis : Make the table above. Provide functions for read/write in table

- [ ]  Get all versions and their dates for a game : 

      `$arraOfVersions = wpunity_get_all_versions_of_game($game_project_id)`

               return  an array of  [ version_number  ,  date_generated], e.g. 

                ```[[1,  2017-10-18 5:00:35], [2, 2017-10-19 6:00:35], [3, 2017-10-19 7:00:35]]```

- [ ] Get the last version for a game should return the max `version_number`  for a certain `game_project_id`

        `$lastverion = wpunity_get_last_version_of_game($game_project_id)`

- [ ] Append new version for a game should add a new record to table 

        $new_version_number = $lastverion + 1;
       `wpunity_append_version_game($game_project_id, $new_version_number, $now_date)` 

@jimver04: In ProjectSettings/ProjectSettings.asset file. The following fields should be modified each time a game is assemblied for compiling

```
metroPackageVersion: X.X.X.X
bundleVersion: X.X.X.X
AndroidBundleVersionCode: XXXX 
buildNumber:
    Standalone: XXXX 
    iOS: XXXX 
```

- [x] Transform ProjectSettings.asset file to template by replacing the aforementioned 

     XXXX   with    `___[game_version_number]___`
     X.X.X.X  with  `___[game_version_number_dotted]___`

- [ ] Before writing them to MyGameUnity/ProjectSettings folder
-- [ ] Get last version from db
-- [ ] Incremement one and append to db
-- [x] Replace XXXX with the number
-- [x] Write the ProjectSettings.asset file

**Comment by jimver04** [comment]
The approach is to make a new table with a counter and the timestamp, 
counter should start from 1 and go to 9999

The counter should correspond to each game. 

The counter should be saved in the ProjectSettings/ProjectSettings.asset file

**Comment by jimver04** [comment]
Possible Bug : bundleVersion gets X.X.X   strictly ?

**Comment by jimver04** [comment]
I have done the functions but it seems  that the activation hook is not working

Taso please check

- WordpressUnity3DEditor-functions.php

// Make the games versions table on activating the plugin
include_once( plugin_dir_path( __FILE__ ) . 'includes/wpunity-db-table-creations.php' );
register_activation_hook( __FILE__, 'wpunity_db_create_games_versions_table' );

Calls are done in L486 of  includes\wpunity-core-project-handler.php

**Comment by tpapaz** [comment]
@jimver04 Done

**Comment by jimver04** [comment]
Thanks to Tasos it is done
