### ISSUE TITLE
Size specification of jpg images 

### ISSUE THREAD

**Issue by jimver04** [DigiArt-project/WordpressUnity3DEditor#180]
We should predefine our jpg images size

- Main menu :   350 w x 200h
- Help :  1200 w x 600 h
- Credits :  512 w x 256 h

and fix the front-end preview images sizes, so that every images is shown without clipping

**Comment by jimver04** [comment]
Taso, whicj jpg sizes are good for the scene tiles in "Project Editor" page ?

**Comment by tpapaz** [comment]
@jimver04 There is no stanadard size. It's adaptive.
