### ISSUE TITLE
Inform the game editors about how to put rich text 

### ISSUE THREAD

**Issue by jimver04** [DigiArt-project/WordpressUnity3DEditor#181]
Taso, 

can we put a popup for the Unity rich text annotation allowed in the text editors?

```
<b>This is bold text</b>
<i>This is italic text</i>
<size=50>This large text</size> 
<color=green>This is green text</color>
<color=#00ffffff>This is custom color text</color>
```
combinations are also valid e.g.

`<b><i><size=50><color=green>This is bold, italic, large, green text</b></i></size></color>`

Details in: https://docs.unity3d.com/Manual/StyledText.html

**Comment by tpapaz** [comment]
Let's freeze this for now

**Comment by jimver04** [comment]
Putting tags was not considered good idea from curators. They are not font of it. They will provide a template for POI-Text. It is addressed in another issue to transform this template into poi-text unity template.
