### ISSUE TITLE
Make a form for modifying "Exam" scene

### ISSUE THREAD

**Issue by jimver04** [DigiArt-project/WordpressUnity3DEditor#190]
Taso make a new php page with a form that it is able to add/remove assets of Asset type "Molecule" in the "Exam" scene 
That is: 

- [x] In Game1 of type "Chemistry"
          -- in Project Editor 
          --- if user presses "Edit" on an scene of type "Exam"
          ---- Load wpunity_2DSceneFormEdit.php
          ----- Retrieve all assets of type "Molecule" that belong to Game1, e.g. H20, CH4, CH3OH
          -------- Present two lists, namely 
          ------------ 1. The list of the available "Molecules", 
          ------------ 2. The list of the molecules in the game. 
          ------   Allow the educator to move molecules from the first list to the second in order to add molecules in the game or from the second to first in order to remove molecules from the game. 

Stathi make the necessary php functions for 
- [x] retrieving assets of type "Molecule" for Game1 of type "Chemistry".
- [x] storing the list of selected molecules as a json file for the scene. Format 

```
{ 
      "objects" :       
                  {

                    "molecule_142315512":
                      {  
                          "asset_id": 15,
                         "asset_type": "molecule",
                         "asset_molecule_type": "H2O",
                         "asset_molecule_name": "Water",
                         "asset_molecule_file": "thepathto/water.pdb" 
                     } 

                    "molecule_142315651":
                      {  
                          "asset_id": 16,
                         "asset_type": "molecule",
                         "asset_molecule_type": "CH4",
                         "asset_molecule_name": "Methane",
                         "asset_molecule_file": "thepathto/methane.pdb" 
                     } 
                       

                 }
}
```

**Comment by stathisnikolaidis** [comment]
The template file is ready.

**Comment by jimver04** [comment]
It was saved as metadata in the scene instead in the json
