### ISSUE TITLE
Middle click on Microscope and on Textbook in 3D editor

### ISSUE THREAD

**Issue by jimver04** [DigiArt-project/wordpressunity3deditor#208]
- [x] Taso  on middle click
    if assetType == "Microscope" || "Textbook"
          display a popup div to select an ExamMicro scene in a dropdown widget 

Put the following dummy data:

```
<select>
Select a scene to load:
<option>First ExamMicro scene</option>
</select>
```

- [ ] Stathi make the php to fetch all ExamMicro scenes of the game

**Comment by tpapaz** [comment]
See vr_editor.php line 319 for component ids.
@jimver04 You check for every middle click inside the canvas? Or do you bind an event to a category of objects?

**Comment by jimver04** [comment]
I do raycasting. If the ray intersects with an object, the object is of a certain category, and the click is middle, display a popup.

**Comment by tpapaz** [comment]
ok, so you can write the code now to show the popup I created.
Right?

**Comment by jimver04** [comment]
Do you mean the old popup of the door  ?

**Comment by tpapaz** [comment]
See vr_editor.php line 319

**Comment by jimver04** [comment]
ok the interface is done. I am waiting for the php
