### ISSUE TITLE
Nearest value of viscosity bug for decimal numbers

### ISSUE THREAD

**Issue by jimver04** [DigiArt-project/WordpressUnity3DEditor#209]
There seems to be a problem with decimal inputs in viscosity. It does not accept decimal values.

![image](https://user-images.githubusercontent.com/1898502/32322259-9561014c-bfcc-11e7-91c0-5fbb78bd1530.png)

**Comment by tpapaz** [comment]
It's not a bug, it's a feature!

I set it up like this intentionally. 
Tell me the step for the value input and I will change it accordingly.

**Comment by jimver04** [comment]
Taso put 0.1 as step
