### ISSUE TITLE
Load local material-icons font instead of CDN

### ISSUE THREAD

**Issue by jimver04** [DigiArt-project/WordpressUnity3DEditor#221]
The directions, labels etc. icons are not shown when offline. 
Can we embody them ?

**Comment by tpapaz** [comment]
We can but I can hardly see the point in doing that. We have other libraries or WordPress features that will not work when offline, so what's the point?

**Comment by jimver04** [comment]
When the internet connection is slow I get a funny image that lasts about 2secs.
It is not urgent, but ...

**Comment by tpapaz** [comment]
ok fair enough, I'll add it.

**Comment by jimver04** [comment]
Here is the problem

![image](https://user-images.githubusercontent.com/1898502/32532418-c2258524-c452-11e7-846b-f379d2862594.png)

Material icons is about 50Kb thats is costing on every page.
