### ISSUE TITLE
3D editor flickering

### ISSUE THREAD

**Issue by jimver04** [DigiArt-project/WordpressUnity3DEditor#227]
See this video: 
https://www.dropbox.com/s/2a5uyhmq3lz29gb/flickering3Deditor.mp4?dl=0

Steps: I make it full screen, add an asset, then make it small screen, there are scrolling bars appearing and dissapearing around the 3d editor

**Comment by tpapaz** [comment]
I can only reproduce this when the dom inspector is on. 
I suppose yours is off?
