### ISSUE TITLE
Visualization of 3d model dimensions  in 3d editor

### ISSUE THREAD

**Issue by jimver04** [DigiArt-project/wordpressunity3deditor#231]
Taso I have calculated the dimensions of the 3d model (dynamically) on auxControlers.js  L23

Can you display these three numbers in a nice way ?
Probably somewhere near to scale widget on upper left

**Comment by tpapaz** [comment]
Does this information need to be editable?

**Comment by jimver04** [comment]
No make it static.
Scaling already covers this functionality.
