### ISSUE TITLE
Why video is not rendered in Unity3D compiled for WebGL?

### ISSUE THREAD

**Issue by jimver04** [DigiArt-project/WordpressUnity3DEditor#253]
Whereas in Windows standalone it plays well, there is no rendering in WebGL.

Tested on Unity3D 2017.1.1

I used the VideoPlayer gameobject from "Assets" menu.

**Comment by jimver04** [comment]
VideoClip is not supported in WebGL
It should be written as URL:  https://forum.unity.com/threads/videoplayer-webgl-url-not-working.467391/

**Comment by PanMig** [comment]
To make it work follow the instructions below 

1) Create a canvas game object
2) Add a UI-> Raw image and position it to the desired coordinates in the screen.
3) Create a scrip with this code inside. [https://github.com/luzan/UnityVideoPlayer/blob/master/Unity%20VideoPlayer%20-%20Part%201/Assets/StreamVideo.cs](url)
4) Apply the script to the raw image texture and set as raw image property this raw image.
5) Open the script and remove the comments from video. url
6) Add comments to the code in video from source
7) Enable cross-origin sharing [https://enable-cors.org/server_apache.html](url)
