### ISSUE TITLE
Exiting "Full Screen" bug

### ISSUE THREAD

**Issue by jimver04** [DigiArt-project/WordpressUnity3DEditor#260]
The "Exit from Full Screen" functionality does not work very well. See image below (Firefox):

![image](https://user-images.githubusercontent.com/1898502/37467573-484ba4ce-2869-11e8-99e8-d713768c685e.png)

**Comment by tpapaz** [comment]
This seems to be a theme specific issue. Cannot reproduce it on my setup.
@jimver04 can you provide me with a url, so I can live test changes?

**Comment by jimver04** [comment]
I am testing it at localhost. I have fixed it.
