### ISSUE TITLE
Ready to use 3D models

### ISSUE THREAD

**Issue by jimver04** [DigiArt-project/WordpressUnity3DEditor#262]
Taso, we want to have some ready to use 3D models that can be selected (as thumbnails) below the 3D viewer (instead of downloading a zip and uploading them)

Taso can you make a carousel or smth  similar (scrollbar horizontal) below the 3D viewer. When an image is selected then the 3D model will be loaded in the 3D viewer (we will make it with Stathis). Just make the front-end interface.

Thanks

**Comment by tpapaz** [comment]
Is this a duplicate of #259?

**Comment by jimver04** [comment]
Ooops yes. I am closing it.
