### ISSUE TITLE
GIO connectivity

### ISSUE THREAD

**Issue by jimver04** [DigiArt-project/wordpressunity3deditor#271]
Taso is the connectivity with GIO achieved when making a new game to get the api keys ?
When I try to create a game then the page dies due to 401 unauthorized access. I found that it is due to wp_remote_post in wpunity-core-functions.php. The response is coming from GIO server not our.  I will remove for the time being the die() calls because the game is created properly (apart the GIO keys).
Instead of die() can you put an alert div on the game project editor in order to remind us that connectivity with GIO is not achieved.

Thanks,
D.

**Comment by tpapaz** [comment]
Can you show me the error?

**Comment by tpapaz** [comment]
It is imperative to stop the user from registering if GIO connectivity is not achieved, because the user will have to create a second account then

**Comment by jimver04** [comment]
It should not stop because it is not more crucial to have analytics than make the game

**Comment by tpapaz** [comment]
Registration works when I try it. @stathisnikolaidis does your commit #271 fixes this?

**Comment by tpapaz** [comment]
Fixed in 1b3c992b632c825f15494b9cf6e1eaa5804eb4f9
