### ISSUE TITLE
Advanced button

### ISSUE THREAD

**Issue by jimver04** [DigiArt-project/wordpressunity3deditor#290]
Can we make the followings to be hidden and shown only if your press an "Advanced" button ?

![image](https://user-images.githubusercontent.com/1898502/39573331-71b2a360-4edb-11e8-88f3-049af9c80752.png)

**Comment by tpapaz** [comment]
What about the 'Assets'?

**Comment by jimver04** [comment]
The Assets in the bottom are necessary in order to know how and which assets are already available in the game, so do not remove them. It was one of the comments in phase I. When you add an asset from the project editor you didn't know if it was created successfully in the game.
