### ISSUE TITLE
Insert information about game values

### ISSUE THREAD

**Issue by PanMig** [DigiArt-project/wordpressunity3deditor#336]
Taso please, add these values below the 3d editor to be seen by the users.

### Average wind speed:

Mountains = 10 m/s
Fields = 8,5 m/s
seashore = 7,5 m/s   

### Access cost:
Mountains = 3 $
Fields = 2  $
Seashore = 1 $

### Turbine Types:
Mountains ( Wind class I ) = A, B, C
Fields ( Wind class II ) = D, E, F
seashore ( Wind class III ) = G, H, I

* letters of turbines corresponds to the Turbine type

**Comment by jimver04** [comment]
Panagioti write also what A, B, C, D, E, F, G, H, I correspond to.

**Comment by tpapaz** [comment]
Check the values and tell me if there is any other information needed
