### ISSUE TITLE
Remaining issues

### ISSUE THREAD

**Issue by jimver04** [DigiArt-project/wordpressunity3deditor#356]
- Wind Energy
     - Compiled game is showing scene selector first
     - Textures in terrains in simulation scenes prevent game to compiled from editor

- Chemistry
     - 1 commit behind the WindEnergy3 branch

**Comment by PanMig** [comment]
The chemistry issue is solved.

The Wind energy issue for textures is solved.

The issue about scene selector seems to be solved, but I will be sure when compiled from the tool and not Unity
