### ISSUE TITLE
Firefox not rendering Asset3D in Creation

### ISSUE THREAD

**Issue by jimver04** [DigiArt-project/WordpressUnity3DEditor#36]
TransformControls.js line 1142
TouchEvent ???

**Comment by tpapaz** [comment]
Update: The TouchEvent error is unrelated.
The real problem resides somewhere in the ajax call for the asset list. It always returns 0.

**Comment by jimver04** [comment]
Taso, I have found it, Firefox has a different start when reading files

Can you apply the following patch ?

at edit-wpunity_asset3D.php    Line 727
                         
// Chrome & Edge
content = content.replace('data:;base64,', '');
                           
// Firefox
content = content.replace('data:application/octet-stream;base64,', '');

Thanx,
D.

**Comment by tpapaz** [comment]
This seems to break the objects when uploading them and making them, undreadable

**Comment by tpapaz** [comment]
1a577995adc2e15e974ef9e2099d56d520089c2a
