### ISSUE TITLE
Wind Energy issues

### ISSUE THREAD

**Issue by PanMig** [DigiArt-project/wordpressunity3deditor#360]
- [ ]  The water shader is changed to standard rather than FX / Water (Basic), same solution that we used in chemistry lab, the problem is in the import settings script.

**Comment by jimver04** [comment]
Which is the name of the .mat of the water ?

**Comment by PanMig** [comment]
Its WaterBasicDaytime.mat

**Comment by jimver04** [comment]
does it have texture ?

**Comment by jimver04** [comment]
Fixed at  9968af9
