### ISSUE TITLE
No scrolling in hierarchy viewer

### ISSUE THREAD

**Issue by jimver04** [DigiArt-project/wordpressunity3deditor#361]
When there many than 10 items the list is out of screen. We need a scrollview.

![image](https://user-images.githubusercontent.com/1898502/45359876-9a3b3380-b5d6-11e8-8ca4-453a91d2aeb6.png)

**Comment by tpapaz** [comment]
Check now after latest commit pleas

**Comment by jimver04** [comment]
Good, but when you close the Hierarchy Viewer you can not re-open it because its button is lost.

**Comment by tpapaz** [comment]
Fixed in commit 6e4a61672310af3e89d7712e3798c61c46f87902

**Comment by jimver04** [comment]
ok nice fix! I am closing it.
