### ISSUE TITLE
Hard keys E,R,W are not functional in 3D editor

### ISSUE THREAD

**Issue by jimver04** [DigiArt-project/WordpressUnity3DEditor#40]
The gizmo should change when I press E or R or W

**Comment by jimver04** [comment]
Also when in "Walk in" mode, keys W,A,S,D are not functional

**Comment by tpapaz** [comment]
I tested walk mode and the keys work.

Actually the keys for the Gizmo are T-R-E. 'T' works btw. Only R & E are note functional.

**Comment by tpapaz** [comment]
Following up: In keyButtons.js the keys are T Y U instead of ERW.
Right?

**Comment by tpapaz** [comment]
T Y U keys are now working
