### ISSUE TITLE
Educational Scene no way to set featured image from front-end

### ISSUE THREAD

**Issue by jimver04** [DigiArt-project/WordpressUnity3DEditor#72]
Taso plz put somewhere I button. In the meanwhile to test compile I need to set featured image from back-end.

**Comment by jimver04** [comment]
Also it does not let me to set featured image from back-end. Dead-end.

HTTP ERROR:
led to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by tpapaz** [comment]
So what are we gonna do with this?
