### ISSUE TITLE
Hierarchy view in Asset 3D editor

### ISSUE THREAD

**Issue by jimver04** [DigiArt-project/wordpressunity3deditor#79]
All game objects should appear in a selectable list

**Comment by tpapaz** [comment]
I forgot about this. Is is a duplicate?

**Comment by jimver04** [comment]
It is a new feature. It is a view that show acually the scene objects that are rendered. Forget it. We will do it when we will finish with the rest of the changes

**Comment by tpapaz** [comment]
I think this is complete

**Comment by jimver04** [comment]
Yes, I am closing it.
