### ISSUE TITLE
3D asset editor - Auto load previews

### ISSUE THREAD

**Issue by tpapaz** [DigiArt-project/WordpressUnity3DEditor#8]
Make the model previewer to load automatically on corresponding asset(s) upload

**Comment by tpapaz** [comment]
Need help from @jimver04 
Inside wpunity-types-assets-viewer there is only JS code  (and no PHP).
Maybe we can save this into a function in a JS file so I can load the function asynchronously to show the object preview from the file inputs.

**Comment by jimver04** [comment]
Fixed !

**Comment by tpapaz** [comment]
Issue is not yet closed. I must implement the view at the front

**Comment by tpapaz** [comment]
0684f1f54e3708deaffdee30ebe19fb7de4c9cf7 closed this issue
