### ISSUE TITLE
Sticky divs in 3d editor evolve theme

### ISSUE THREAD

**Issue by jimver04** [DigiArt-project/WordpressUnity3DEditor#87]
These seem to solve the problem with overlaying divs on top of 3d editor. Taso can we pass them to the css of our plugin ?

#backtotop   

        z-index : 9999     ->   100

#header.sticky-header {        // multiples for each resolution

       z-index : 99998   -> 100

**Comment by tpapaz** [comment]
closed in 2a4ac4afa6bd59b7f1ea9035314583e8cfab306d
