### ISSUE TITLE
Divs with class "ProducerPlotTooltip" should be not displayed

### ISSUE THREAD

**Issue by jimver04** [DigiArt-project/WordpressUnity3DEditor#91]
The plot numbers appear on Creating new Asset before selecting category.

On create new asset the set display:none to ProducerPlotTooltip class with jQuery css command or css

**Comment by tpapaz** [comment]
41641af1e2e9f9f80d9b262da7996a55f9a91a06

**Comment by jimver04** [comment]
Taso to ProducerPlotTooltip emfanizetai afou dialeksw to category decoration kai patisw to "Select an MTL file"

**Comment by tpapaz** [comment]
Fixed the right one in 7c2bf268d0d019d8fdc1f0904e42406efa1e5169
