### ISSUE TITLE
Image for educational scenes?

### ISSUE THREAD

**Issue by jimver04** [DigiArt-project/WordpressUnity3DEditor#98]
How to set featured image for the first scene ?
How to edit featured images for the second, third, fourth educational scenes ?

Custom image or screenshot ?

**Comment by stathisnikolaidis** [comment]
$attachment_id = wpunity_upload_Assetimg64($screenShotFile, $asset_information['post_title'], $scene_id, $gameSlug);
set_post_thumbnail( $scene_id, $attachment_id );

**Comment by jimver04** [comment]
It is done as automatic screenshot on press "Save Scene" inside 3d editor
- Scene screenshot for featured image ready
